services:
  agentscrum.web:
    image: agentscrum.web
    container_name: web
    build:
      context: .
      dockerfile: AgentScrum.Web/Dockerfile
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=agentscrum;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - GroqApiKey=your-groq-api-key-placeholder
    ports:
      - "5555:5000"
    networks:
      - agentscrum-network

  postgres:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agentscrum
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - agentscrum-network

volumes:
  postgres-data:

networks:
  agentscrum-network:
    driver: bridge
